# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pontius < Formula
  desc "Terminal email client for AI-assisted email management"
  homepage "https://getpontius.com"
  version "2.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_darwin_amd64.tar.gz"
      sha256 "b47d1057ae7d589e91a9352bde0de8010156df69af6f3629b396ed3c61bbf37c"

      define_method(:install) do
        bin.install "pontius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_darwin_arm64.tar.gz"
      sha256 "2d731432b06137b6eedfe40cb00ef1aeb35a3034c267761a4758ca7ffa9277d0"

      define_method(:install) do
        bin.install "pontius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_linux_amd64.tar.gz"
      sha256 "b44dcca5ce93679df9c3384e0197cb2a1d64b77ca50ea28745465d218132c606"
      define_method(:install) do
        bin.install "pontius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_linux_arm64.tar.gz"
      sha256 "e4a2d6f5cbf84f60354766375e26f9396c28ccd43e3099ad70a5954683533713"
      define_method(:install) do
        bin.install "pontius"
      end
    end
  end

  test do
    system "#{bin}/pontius", "version"
  end
end
