# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pontius < Formula
  desc "Terminal email client for AI-assisted email management"
  homepage "https://getpontius.com"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v1.0.0/pontius_1.0.0_darwin_amd64.tar.gz"
      sha256 "318336eb16f7e42b106b4411412a02387b3eefc5a39f23a753db41ddc37a58c0"

      def install
        bin.install "pontius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v1.0.0/pontius_1.0.0_darwin_arm64.tar.gz"
      sha256 "56c66b4fdda6c9a2fcfd1d41b355d7f7e9bd852ad2a0e4a31ce8c734858eb144"

      def install
        bin.install "pontius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v1.0.0/pontius_1.0.0_linux_amd64.tar.gz"
      sha256 "80f532dbcca33871124df5aa49889c87c46493172fc561219d96b15adc6df7b0"
      def install
        bin.install "pontius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v1.0.0/pontius_1.0.0_linux_arm64.tar.gz"
      sha256 "d4b22ec360126a2ebea6a8deda3b677eeac52171896089cb0baeecacafa80d75"
      def install
        bin.install "pontius"
      end
    end
  end

  test do
    system "#{bin}/pontius", "version"
  end
end
