# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pontius < Formula
  desc "Terminal email client for AI-assisted email management"
  homepage "https://getpontius.com"
  version "2.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_darwin_amd64.tar.gz"
      sha256 "4809984293cce501d4a6c425422920ebe1e05f52e83e763a3d2d2fe7ec18126c"

      define_method(:install) do
        bin.install "pontius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_darwin_arm64.tar.gz"
      sha256 "f8d4170d35f5227436b59a323672cab61eb3615650c3ff343e93601d0b23de3c"

      define_method(:install) do
        bin.install "pontius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_linux_amd64.tar.gz"
      sha256 "54a790cde3f48fdad966b5f9a7e23c5794f367bb0486a05257e333851273182a"
      define_method(:install) do
        bin.install "pontius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuJLans/pontius-releases/releases/download/v2.0.0/pontius_2.0.0_linux_arm64.tar.gz"
      sha256 "8a155d9ad08ff73b259b85c3df4797f5fec4fb5faa1c0442e110549fe0609b71"
      define_method(:install) do
        bin.install "pontius"
      end
    end
  end

  test do
    system "#{bin}/pontius", "version"
  end
end
